version: "3"
services:
  ecommerce-php:
    build: .
    image: ecommerce-php-image
    container_name: ecommerce-php
    ports:
    - 9001:9001
    volumes:
    - ./application:/application
    networks:
      - bubble

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - bubble
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - bubble
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    restart: unless-stopped
    networks:
      - bubble
    ports:
      - 7001:8080
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:19092

networks:
  bubble:
    external: true