version: "3"
services:
  ecommerce-php:
    build: .
    image: ecommerce-php-image
    container_name: ecommerce-php
    ports:
    - 9001:9001
    volumes:
    - ./application:/application
    networks:
      - bubble

networks:
  bubble:
    external: true